# Generated by Django 4.0.4 on 2022-06-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_addtocart_county_customer_customeraddress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddToCart',
        ),
    ]
