# Generated by Django 4.0.4 on 2022-06-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='secondname',
        ),
    ]
