# Generated by Django 4.0.4 on 2022-06-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_customer_firstname_remove_customer_secondname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
