# Generated by Django 4.0.4 on 2022-06-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_customer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='seller',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='seller_images'),
        ),
    ]
