# Generated by Django 4.0.4 on 2022-06-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_remove_customer_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='OTP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='coupon_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
