# Generated by Django 4.0.4 on 2022-06-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_customer_otp_alter_customer_coupon_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
