# Generated by Django 4.0.4 on 2022-06-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_customer_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to='staff.customer'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
