# Generated by Django 4.0.4 on 2022-06-07 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.productimage'),
        ),
    ]
