# Generated by Django 4.0.4 on 2022-06-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_rename_image_productimage_image1_productimage_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
