# Generated by Django 4.0.4 on 2022-06-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image4',
        ),
    ]
