# Generated by Django 4.0.4 on 2022-06-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_rename_image1_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
    ]
