# Generated by Django 4.0.4 on 2022-06-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_remove_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
