# Generated by Django 4.0.4 on 2022-06-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
