# Generated by Django 4.0.4 on 2022-06-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_alter_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
