# Generated by Django 4.0.4 on 2022-06-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_remove_cart_quantity_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
