# Generated by Django 4.0.4 on 2022-06-16 01:14

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_qty',
            field=models.IntegerField(default=1, verbose_name=django.contrib.auth.models.User),
        ),
    ]
