# Generated by Django 4.0.4 on 2022-06-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0034_alter_product_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_cart',
            field=models.ManyToManyField(blank=True, related_name='user_cart', to='staff.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to='staff.customer'),
        ),
    ]
