# Generated by Django 4.0.4 on 2022-06-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0036_alter_product_user_cart_alter_product_user_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_qty',
        ),
        migrations.AddField(
            model_name='product',
            name='order_status',
            field=models.CharField(blank=True, default='new', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_qty',
            field=models.IntegerField(default=1),
        ),
    ]
