# Generated by Django 4.0.4 on 2022-06-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0038_remove_product_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_qty',
            field=models.IntegerField(null=True),
        ),
    ]
