# Generated by Django 4.0.4 on 2022-06-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0042_remove_cart_product_remove_cart_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_cart',
        ),
    ]
